#!/bin/bash

# Copyright (c) 2020 Peter Nemeth. All rights reserved.
# 
# This work is licensed under the terms of the MIT license.  
# For a copy, see <https://opensource.org/licenses/MIT>.

eval $@
